In [157]:
import pandas as pd

In [158]:
datos = {
    "edad": [16, 30, 22],
    "peso_kg": [70, 80, 75],
    "objetivo": ["ganar fuerza", "bajar peso", "mejorar resistencia"]
}

In [159]:
usuarios_df = pd.DataFrame(datos)
usuarios_df

   edad  peso_kg             objetivo
0    16       70         ganar fuerza
1    30       80           bajar peso
2    22       75  mejorar resistencia

In [160]:
usuarios_df.shape

(3, 3)

In [161]:
usuarios_df["dias_disponibles"]= ["3", "5", "2"]

In [162]:
usuarios_df

   edad  peso_kg             objetivo dias_disponibles
0    16       70         ganar fuerza                3
1    30       80           bajar peso                5
2    22       75  mejorar resistencia                2

In [163]:
usuarios_df["tiempo_disponible"] = ["30", "120", "50"]

In [164]:
usuarios_df["experiencia"] = ["principiante", "intermedio", "avanzado"]

In [165]:
usuarios_df["lugar_entrenamiento"] = ["gym", "hogar","aire libre"]

In [166]:
usuarios_df["Dificultad"] = ["Facil", "Medio","Dificil"]

In [167]:
usuarios_df["lesiones"] = ["nada", "Espalda","Pierna"]

In [168]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna

In [169]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna

In [170]:
X = usuarios_df.drop(columns=["Dificultad"])

In [171]:
y = usuarios_df["Dificultad"]

In [172]:
X

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Pierna

In [173]:
y

0      Facil
1      Medio
2    Dificil
Name: Dificultad, dtype: object

In [174]:
X_convertido = pd.get_dummies(X)

In [175]:
X_convertido

,edad,peso_kg,objetivo_bajar peso,objetivo_ganar fuerza,objetivo_mejorar resistencia,dias_disponibles_2,dias_disponibles_3,dias_disponibles_5,tiempo_disponible_120,tiempo_disponible_30,tiempo_disponible_50,experiencia_avanzado,experiencia_intermedio,experiencia_principiante,lugar_entrenamiento_aire libre,lugar_entrenamiento_gym,lugar_entrenamiento_hogar,lesiones_Espalda,lesiones_Pierna,lesiones_nada
0,16,70,False,True,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,True
1,30,80,True,False,False,False,False,True,True,False,False,False,True,False,False,False,True,True,False,False
2,22,75,False,False,True,True,False,False,False,False,True,True,False,False,True,False,False,False,True,False

In [176]:
X["dias_disponibles"] = X["dias_disponibles"].astype(int)
X["tiempo_disponible"] = X["tiempo_disponible"].astype(int)

In [177]:
X_convertido = pd.get_dummies(X)

In [178]:
X_convertido

,edad,peso_kg,dias_disponibles,tiempo_disponible,objetivo_bajar peso,objetivo_ganar fuerza,objetivo_mejorar resistencia,experiencia_avanzado,experiencia_intermedio,experiencia_principiante,lugar_entrenamiento_aire libre,lugar_entrenamiento_gym,lugar_entrenamiento_hogar,lesiones_Espalda,lesiones_Pierna,lesiones_nada
0,16,70,3,30,False,True,False,False,False,True,False,True,False,False,False,True
1,30,80,5,120,True,False,False,False,True,False,False,False,True,True,False,False
2,22,75,2,50,False,False,True,True,False,False,True,False,False,False,True,False

In [179]:
y_convertido = y.map({
    "Facil": 0,
    "Medio": 1,
    "Dificil": 2
})

In [180]:
y_convertido

0    0
1    1
2    2
Name: Dificultad, dtype: int64

In [181]:
nuevos_usuarios = pd.DataFrame({
    "edad": [18, 25, 40, 35, 28, 50, 21, 33, 45, 27, 19, 38],
    "peso_kg": [68, 82, 90, 74, 77, 95, 65, 88, 85, 72, 69, 80],
    "objetivo": [
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia",
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia",
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia",
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia"
    ],
    "dias_disponibles": [4, 3, 2, 5, 4, 2, 3, 5, 2, 4, 3, 5],
    "tiempo_disponible": [45, 60, 30, 90, 50, 40, 35, 120, 45, 60, 30, 75],
    "experiencia": [
        "principiante",
        "intermedio",
        "principiante",
        "avanzado",
        "intermedio",
        "principiante",
        "principiante",
        "avanzado",
        "intermedio",
        "intermedio",
        "principiante",
        "avanzado"
    ],
    "lugar_entrenamiento": [
        "gym",
        "hogar",
        "aire libre",
        "gym",
        "hogar",
        "aire libre",
        "hogar",
        "gym",
        "aire libre",
        "gym",
        "hogar",
        "gym"
    ],
    "Dificultad": [
        "Facil",
        "Medio",
        "Facil",
        "Dificil",
        "Medio",
        "Facil",
        "Facil",
        "Dificil",
        "Medio",
        "Medio",
        "Facil",
        "Dificil"
    ],
    "lesiones": [
        "nada",
        "nada",
        "Espalda",
        "nada",
        "Pierna",
        "Espalda",
        "nada",
        "nada",
        "Pierna",
        "nada",
        "nada",
        "Espalda"
    ]
})

In [182]:
usuarios_df = pd.concat([usuarios_df, nuevos_usuarios], ignore_index=True)

In [183]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna
3,18,68,ganar fuerza,4,45,principiante,gym,Facil,nada
4,25,82,bajar peso,3,60,intermedio,hogar,Medio,nada
5,40,90,mejorar resistencia,2,30,principiante,aire libre,Facil,Espalda
6,35,74,ganar fuerza,5,90,avanzado,gym,Dificil,nada
7,28,77,bajar peso,4,50,intermedio,hogar,Medio,Pierna
8,50,95,mejorar resistencia,2,40,principiante,aire libre,Facil,Espalda
9,21,65,ganar fuerza,3,35,principiante,hogar,Facil,nada
10,33,88,bajar peso,5,120,avanzado,gym,Dificil,nada
11,45,85,mejorar resistencia,2,45,intermedio,aire libre,Medio,Pierna
12,27,72,ganar fuerza,4,60,intermedio,gym,Medio,nada
13,19,69,bajar peso,3,30,principiante,hogar,Facil,nada
14,38,80,mejorar resistencia,5,75,avanzado,gym,Dificil,Espalda

In [184]:
X = usuarios_df.drop(columns=["Dificultad"])
y = usuarios_df["Dificultad"]

In [185]:
X["dias_disponibles"] = X["dias_disponibles"].astype(int)
X["tiempo_disponible"] = X["tiempo_disponible"].astype(int)

X_convertido = pd.get_dummies(X)

In [186]:
y_convertido = y.map({
    "Facil": 0,
    "Medio": 1,
    "Dificil": 2
})

In [187]:
X_convertido.shape

(15, 16)

In [188]:
from sklearn.model_selection import train_test_split

In [189]:
X_train, X_test, y_train, y_test = train_test_split(
    X_convertido,
    y_convertido,
    test_size=0.2,
    random_state=42
)

In [190]:
X_train.shape

(12, 16)

In [191]:
X_test.shape

(3, 16)

In [192]:
from sklearn.tree import DecisionTreeClassifier

In [193]:
modelo = DecisionTreeClassifier(random_state=42)

In [194]:
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [195]:
predicciones = modelo.predict(X_test)

In [196]:
predicciones

array([0, 1, 0], dtype=int64)

In [197]:
y_test

9     0
11    1
0     0
Name: Dificultad, dtype: int64

In [198]:
from sklearn.metrics import accuracy_score

In [199]:
precision = accuracy_score(y_test, predicciones)
precision

1.0

In [200]:
usuarios_df.shape

(15, 9)

In [201]:
print("Reales:", y_test.values)
print("Predicciones:", predicciones)

Reales: [0 1 0]
Predicciones: [0 1 0]

In [203]:
print(X_convertido.shape)
print(y_convertido.shape)

(15, 16)
(15,)

In [204]:
nuevo_usuario = pd.DataFrame({
    "edad": [24],
    "peso_kg": [78],
    "objetivo": ["ganar fuerza"],
    "dias_disponibles": [4],
    "tiempo_disponible": [60],
    "experiencia": ["intermedio"],
    "lugar_entrenamiento": ["gym"],
    "lesiones": ["nada"]
})

In [205]:
nuevo_usuario

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,lesiones
0,24,78,ganar fuerza,4,60,intermedio,gym,nada

In [206]:
nuevo_convertido = pd.get_dummies(nuevo_usuario)

In [207]:
nuevo_convertido = nuevo_convertido.reindex(
    columns=X_convertido.columns,
    fill_value=False
)

In [208]:
prediccion_nueva = modelo.predict(nuevo_convertido)
prediccion_nueva

array([1], dtype=int64)

In [209]:
dificultades = {
    0: "Facil",
    1: "Medio",
    2: "Dificil"
}

In [210]:
resultado = dificultades[prediccion_nueva[0]]
resultado

'Medio'

In [211]:
def predecir_dificultad(edad, peso, objetivo, dias, tiempo, experiencia, lugar, lesiones):
    usuario = pd.DataFrame({
        "edad": [edad],
        "peso_kg": [peso],
        "objetivo": [objetivo],
        "dias_disponibles": [dias],
        "tiempo_disponible": [tiempo],
        "experiencia": [experiencia],
        "lugar_entrenamiento": [lugar],
        "lesiones": [lesiones]
    })

    usuario_convertido = pd.get_dummies(usuario)

    usuario_convertido = usuario_convertido.reindex(
        columns=X_convertido.columns,
        fill_value=False
    )

    prediccion = modelo.predict(usuario_convertido)[0]

    dificultades = {
        0: "Facil",
        1: "Medio",
        2: "Dificil"
    }

    return dificultades[prediccion]

In [212]:
predecir_dificultad(
    26,
    76,
    "ganar fuerza",
    4,
    60,
    "intermedio",
    "gym",
    "nada"
)

'Medio'

In [213]:
predecir_dificultad(
    45,
    90,
    "bajar peso",
    2,
    30,
    "principiante",
    "hogar",
    "Espalda"
)

'Facil'

In [215]:
modelo.feature_importances_

array([0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0. ,
       0. , 0. , 0. ])

In [216]:
importancias = pd.Series(
    modelo.feature_importances_,
    index=X_convertido.columns
)

importancias.sort_values(ascending=False)

tiempo_disponible                 0.5
experiencia_intermedio            0.5
edad                              0.0
peso_kg                           0.0
dias_disponibles                  0.0
objetivo_bajar peso               0.0
objetivo_ganar fuerza             0.0
objetivo_mejorar resistencia      0.0
experiencia_avanzado              0.0
experiencia_principiante          0.0
lugar_entrenamiento_aire libre    0.0
lugar_entrenamiento_gym           0.0
lugar_entrenamiento_hogar         0.0
lesiones_Espalda                  0.0
lesiones_Pierna                   0.0
lesiones_nada                     0.0
dtype: float64