In [1]:
import pandas as pd

In [2]:
datos = {
    "edad": [16, 30, 22],
    "peso_kg": [70, 80, 75],
    "objetivo": ["ganar fuerza", "bajar peso", "mejorar resistencia"]
}

In [3]:
usuarios_df = pd.DataFrame(datos)
usuarios_df

   edad  peso_kg             objetivo
0    16       70         ganar fuerza
1    30       80           bajar peso
2    22       75  mejorar resistencia

In [4]:
usuarios_df.shape

(3, 3)

In [28]:
usuarios_df["dias_disponibles"]= ["3", "5", "2"]

In [10]:
usuarios_df

   edad  peso_kg             objetivo dias_disponibles
0    16       70         ganar fuerza            Lunes
1    30       80           bajar peso           jueves
2    22       75  mejorar resistencia         domingos

In [12]:
usuarios_df["tiempo_disponible"] = ["30", "120", "50"]

In [37]:
usuarios_df["experiencia"] = ["principiante", "intermedio", "avanzado"]

In [17]:
usuarios_df["lugar_entrenamiento"] = ["gym", "hogar","aire libre"]

In [30]:
usuarios_df["Dificultad"] = ["Facil", "Medio","Dificil"]

In [25]:
usuarios_df = usuarios_df.drop(columns=["experencia"])

In [38]:
usuarios_df["lesiones"] = ["nada", "Espalda","Pierna"]

In [41]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna

In [40]:
usuarios_df = usuarios_df.drop(columns=["lesiines"])