In [2]:
import pandas as pd

In [4]:
datos = {
    "edad": [16, 30, 22],
    "peso_kg": [70, 80, 75],
    "objetivo": ["ganar fuerza", "bajar peso", "mejorar resistencia"]
}

In [5]:
usuarios_df = pd.DataFrame(datos)
usuarios_df

   edad  peso_kg             objetivo
0    16       70         ganar fuerza
1    30       80           bajar peso
2    22       75  mejorar resistencia

In [4]:
usuarios_df.shape

(3, 3)

In [6]:
usuarios_df["dias_disponibles"]= ["3", "5", "2"]

In [10]:
usuarios_df

   edad  peso_kg             objetivo dias_disponibles
0    16       70         ganar fuerza            Lunes
1    30       80           bajar peso           jueves
2    22       75  mejorar resistencia         domingos

In [8]:
usuarios_df["tiempo_disponible"] = ["30", "120", "50"]

In [13]:
usuarios_df["experiencia"] = ["principiante", "intermedio", "avanzado"]

In [10]:
usuarios_df["lugar_entrenamiento"] = ["gym", "hogar","aire libre"]

In [11]:
usuarios_df["Dificultad"] = ["Facil", "Medio","Dificil"]

In [14]:
usuarios_df = usuarios_df.drop(columns=["experencia"])

KeyError: "['experencia'] not found in axis"

In [15]:
usuarios_df["lesiones"] = ["nada", "Espalda","Pierna"]

In [16]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna

In [17]:
usuarios_df = usuarios_df.drop(columns=["lesiines"])

KeyError: "['lesiines'] not found in axis"

In [18]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna

In [19]:
X = usuarios_df.drop(columns=["Dificultad"])

In [20]:
y = usuarios_df["Dificultad"]

In [22]:
X

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Pierna

In [23]:
y

0      Facil
1      Medio
2    Dificil
Name: Dificultad, dtype: object

In [25]:
X_convertido = pd.get_dummies(X)

In [26]:
X_convertido

,edad,peso_kg,objetivo_bajar peso,objetivo_ganar fuerza,objetivo_mejorar resistencia,dias_disponibles_2,dias_disponibles_3,dias_disponibles_5,tiempo_disponible_120,tiempo_disponible_30,tiempo_disponible_50,experiencia_avanzado,experiencia_intermedio,experiencia_principiante,lugar_entrenamiento_aire libre,lugar_entrenamiento_gym,lugar_entrenamiento_hogar,lesiones_Espalda,lesiones_Pierna,lesiones_nada
0,16,70,False,True,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,True
1,30,80,True,False,False,False,False,True,True,False,False,False,True,False,False,False,True,True,False,False
2,22,75,False,False,True,True,False,False,False,False,True,True,False,False,True,False,False,False,True,False

In [27]:
X["dias_disponibles"] = X["dias_disponibles"].astype(int)
X["tiempo_disponible"] = X["tiempo_disponible"].astype(int)

In [28]:
X_convertido = pd.get_dummies(X)

In [29]:
X_convertido

,edad,peso_kg,dias_disponibles,tiempo_disponible,objetivo_bajar peso,objetivo_ganar fuerza,objetivo_mejorar resistencia,experiencia_avanzado,experiencia_intermedio,experiencia_principiante,lugar_entrenamiento_aire libre,lugar_entrenamiento_gym,lugar_entrenamiento_hogar,lesiones_Espalda,lesiones_Pierna,lesiones_nada
0,16,70,3,30,False,True,False,False,False,True,False,True,False,False,False,True
1,30,80,5,120,True,False,False,False,True,False,False,False,True,True,False,False
2,22,75,2,50,False,False,True,True,False,False,True,False,False,False,True,False

In [30]:
y_convertido = y.map({
    "Facil": 0,
    "Medio": 1,
    "Dificil": 2
})

In [31]:
y_convertido

0    0
1    1
2    2
Name: Dificultad, dtype: int64

In [34]:
nuevos_usuarios = pd.DataFrame({
    "edad": [18, 25, 40, 35, 28, 50, 21, 33, 45, 27, 19, 38],
    "peso_kg": [68, 82, 90, 74, 77, 95, 65, 88, 85, 72, 69, 80],
    "objetivo": [
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia",
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia",
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia",
        "ganar fuerza",
        "bajar peso",
        "mejorar resistencia"
    ],
    "dias_disponibles": [4, 3, 2, 5, 4, 2, 3, 5, 2, 4, 3, 5],
    "tiempo_disponible": [45, 60, 30, 90, 50, 40, 35, 120, 45, 60, 30, 75],
    "experiencia": [
        "principiante",
        "intermedio",
        "principiante",
        "avanzado",
        "intermedio",
        "principiante",
        "principiante",
        "avanzado",
        "intermedio",
        "intermedio",
        "principiante",
        "avanzado"
    ],
    "lugar_entrenamiento": [
        "gym",
        "hogar",
        "aire libre",
        "gym",
        "hogar",
        "aire libre",
        "hogar",
        "gym",
        "aire libre",
        "gym",
        "hogar",
        "gym"
    ],
    "Dificultad": [
        "Facil",
        "Medio",
        "Facil",
        "Dificil",
        "Medio",
        "Facil",
        "Facil",
        "Dificil",
        "Medio",
        "Medio",
        "Facil",
        "Dificil"
    ],
    "lesiones": [
        "nada",
        "nada",
        "Espalda",
        "nada",
        "Pierna",
        "Espalda",
        "nada",
        "nada",
        "Pierna",
        "nada",
        "nada",
        "Espalda"
    ]
})

In [35]:
usuarios_df = pd.concat([usuarios_df, nuevos_usuarios], ignore_index=True)

In [36]:
usuarios_df

,edad,peso_kg,objetivo,dias_disponibles,tiempo_disponible,experiencia,lugar_entrenamiento,Dificultad,lesiones
0,16,70,ganar fuerza,3,30,principiante,gym,Facil,nada
1,30,80,bajar peso,5,120,intermedio,hogar,Medio,Espalda
2,22,75,mejorar resistencia,2,50,avanzado,aire libre,Dificil,Pierna
3,18,68,ganar fuerza,4,45,principiante,gym,Facil,nada
4,25,82,bajar peso,3,60,intermedio,hogar,Medio,nada
5,40,90,mejorar resistencia,2,30,principiante,aire libre,Facil,Espalda
6,35,74,ganar fuerza,5,90,avanzado,gym,Dificil,nada
7,28,77,bajar peso,4,50,intermedio,hogar,Medio,Pierna
8,50,95,mejorar resistencia,2,40,principiante,aire libre,Facil,Espalda
9,21,65,ganar fuerza,3,35,principiante,hogar,Facil,nada
10,33,88,bajar peso,5,120,avanzado,gym,Dificil,nada
11,45,85,mejorar resistencia,2,45,intermedio,aire libre,Medio,Pierna
12,27,72,ganar fuerza,4,60,intermedio,gym,Medio,nada
13,19,69,bajar peso,3,30,principiante,hogar,Facil,nada
14,38,80,mejorar resistencia,5,75,avanzado,gym,Dificil,Espalda

In [37]:
X = usuarios_df.drop(columns=["Dificultad"])
y = usuarios_df["Dificultad"]

In [38]:
X["dias_disponibles"] = X["dias_disponibles"].astype(int)
X["tiempo_disponible"] = X["tiempo_disponible"].astype(int)

X_convertido = pd.get_dummies(X)

In [39]:
y_convertido = y.map({
    "Facil": 0,
    "Medio": 1,
    "Dificil": 2
})

In [40]:
X_convertido.shape

(15, 16)

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X_convertido,
    y_convertido,
    test_size=0.2,
    random_state=42
)

In [43]:
X_train.shape

(12, 16)

In [44]:
X_test.shape

(3, 16)

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
modelo = DecisionTreeClassifier(random_state=42)

In [47]:
modelo.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [48]:
predicciones = modelo.predict(X_test)

In [49]:
predicciones

array([0, 1, 0], dtype=int64)

In [50]:
y_test

9     0
11    1
0     0
Name: Dificultad, dtype: int64